name: Run E2E Tests
on:
  push:
  pull_request:
    paths:
      - "puppet/**"
  workflow_dispatch:
  
jobs:
  test:
    defaults:
      run:
        working-directory: tests
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
          cache: 'pip'
      - name: pip Install
        run: pip install -r requirements.txt
      - name: Run Tests
        run: python test_sauce_labs.py
        env: 
          SAUCE_ACCESS_KEY: '${{ secrets.SAUCE_ACCESS_KEY}}'
          SAUCE_USERNAME: '${{ secrets.SAUCE_USERNAME}}'
          TEST_UUID: '${{ secrets.TEST_UUID}}'
